# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settingsui.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingsUI(object):
    def setupUi(self, SettingsUI):
        SettingsUI.setObjectName("SettingsUI")
        SettingsUI.resize(500, 540)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SettingsUI.sizePolicy().hasHeightForWidth())
        SettingsUI.setSizePolicy(sizePolicy)
        SettingsUI.setMinimumSize(QtCore.QSize(500, 540))
        SettingsUI.setMaximumSize(QtCore.QSize(500, 540))
        self.tabWidget = QtWidgets.QTabWidget(SettingsUI)
        self.tabWidget.setGeometry(QtCore.QRect(6, 9, 490, 491))
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.generalTab = QtWidgets.QWidget()
        self.generalTab.setObjectName("generalTab")
        self.line_1 = QtWidgets.QFrame(self.generalTab)
        self.line_1.setGeometry(QtCore.QRect(10, 70, 460, 20))
        self.line_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_1.setObjectName("line_1")
        self.quality_ComboBox = QtWidgets.QComboBox(self.generalTab)
        self.quality_ComboBox.setGeometry(QtCore.QRect(250, 40, 220, 22))
        self.quality_ComboBox.setObjectName("quality_ComboBox")
        self.quality_ComboBox.addItem("")
        self.quality_ComboBox.addItem("")
        self.label_1 = QtWidgets.QLabel(self.generalTab)
        self.label_1.setGeometry(QtCore.QRect(20, 40, 220, 21))
        self.label_1.setObjectName("label_1")
        self.monitor_Label = QtWidgets.QLabel(self.generalTab)
        self.monitor_Label.setGeometry(QtCore.QRect(20, 60, 220, 21))
        self.monitor_Label.setObjectName("monitor_Label")
        self.monitor_ComboBox = QtWidgets.QComboBox(self.generalTab)
        self.monitor_ComboBox.setGeometry(QtCore.QRect(250, 60, 220, 22))
        self.monitor_ComboBox.setObjectName("monitor_ComboBox")
        self.label_4 = QtWidgets.QLabel(self.generalTab)
        self.label_4.setGeometry(QtCore.QRect(20, 130, 220, 20))
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(self.generalTab)
        self.label_7.setGeometry(QtCore.QRect(380, 110, 85, 20))
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.generalTab)
        self.label_9.setGeometry(QtCore.QRect(380, 150, 85, 20))
        self.label_9.setObjectName("label_9")
        self.ctrl_y_LineEdit = QtWidgets.QLineEdit(self.generalTab)
        self.ctrl_y_LineEdit.setGeometry(QtCore.QRect(250, 110, 120, 20))
        self.ctrl_y_LineEdit.setObjectName("ctrl_y_LineEdit")
        self.clear_coords_PushButton = QtWidgets.QPushButton(self.generalTab)
        self.clear_coords_PushButton.setGeometry(QtCore.QRect(20, 180, 160, 28))
        self.clear_coords_PushButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.clear_coords_PushButton.setDefault(False)
        self.clear_coords_PushButton.setObjectName("clear_coords_PushButton")
        self.ctrl_h_LineEdit = QtWidgets.QLineEdit(self.generalTab)
        self.ctrl_h_LineEdit.setGeometry(QtCore.QRect(250, 150, 120, 20))
        self.ctrl_h_LineEdit.setObjectName("ctrl_h_LineEdit")
        self.ctrl_w_LineEdit = QtWidgets.QLineEdit(self.generalTab)
        self.ctrl_w_LineEdit.setGeometry(QtCore.QRect(250, 130, 120, 20))
        self.ctrl_w_LineEdit.setObjectName("ctrl_w_LineEdit")
        self.label_2 = QtWidgets.QLabel(self.generalTab)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 220, 20))
        self.label_2.setObjectName("label_2")
        self.label_8 = QtWidgets.QLabel(self.generalTab)
        self.label_8.setGeometry(QtCore.QRect(380, 130, 85, 20))
        self.label_8.setObjectName("label_8")
        self.label_6 = QtWidgets.QLabel(self.generalTab)
        self.label_6.setGeometry(QtCore.QRect(380, 90, 85, 20))
        self.label_6.setObjectName("label_6")
        self.ctrl_x_LineEdit = QtWidgets.QLineEdit(self.generalTab)
        self.ctrl_x_LineEdit.setGeometry(QtCore.QRect(250, 90, 120, 20))
        self.ctrl_x_LineEdit.setObjectName("ctrl_x_LineEdit")
        self.label_5 = QtWidgets.QLabel(self.generalTab)
        self.label_5.setGeometry(QtCore.QRect(20, 150, 220, 20))
        self.label_5.setObjectName("label_5")
        self.label_3 = QtWidgets.QLabel(self.generalTab)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 220, 20))
        self.label_3.setObjectName("label_3")
        self.topmost_CheckBox = QtWidgets.QCheckBox(self.generalTab)
        self.topmost_CheckBox.setGeometry(QtCore.QRect(20, 20, 450, 17))
        self.topmost_CheckBox.setChecked(True)
        self.topmost_CheckBox.setObjectName("topmost_CheckBox")
        self.line_7 = QtWidgets.QFrame(self.generalTab)
        self.line_7.setGeometry(QtCore.QRect(10, 215, 460, 20))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.skip_background_CheckBox = QtWidgets.QCheckBox(self.generalTab)
        self.skip_background_CheckBox.setGeometry(QtCore.QRect(20, 240, 450, 17))
        self.skip_background_CheckBox.setChecked(True)
        self.skip_background_CheckBox.setObjectName("skip_background_CheckBox")
        self.label_13 = QtWidgets.QLabel(self.generalTab)
        self.label_13.setGeometry(QtCore.QRect(20, 265, 220, 21))
        self.label_13.setObjectName("label_13")
        self.color_picker_PushButton = QtWidgets.QPushButton(self.generalTab)
        self.color_picker_PushButton.setGeometry(QtCore.QRect(430, 265, 40, 22))
        self.color_picker_PushButton.setObjectName("color_picker_PushButton")
        self.background_LineEdit = QtWidgets.QLineEdit(self.generalTab)
        self.background_LineEdit.setGeometry(QtCore.QRect(250, 265, 170, 22))
        self.background_LineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.background_LineEdit.setReadOnly(True)
        self.background_LineEdit.setObjectName("background_LineEdit")
        self.skip_colors_ListWidget = QtWidgets.QListWidget(self.generalTab)
        self.skip_colors_ListWidget.setGeometry(QtCore.QRect(20, 325, 320, 111))
        self.skip_colors_ListWidget.setObjectName("skip_colors_ListWidget")
        self.add_skip_color_PushButton = QtWidgets.QPushButton(self.generalTab)
        self.add_skip_color_PushButton.setGeometry(QtCore.QRect(350, 325, 120, 28))
        self.add_skip_color_PushButton.setObjectName("add_skip_color_PushButton")
        self.remove_skip_color_PushButton = QtWidgets.QPushButton(self.generalTab)
        self.remove_skip_color_PushButton.setGeometry(QtCore.QRect(350, 360, 120, 28))
        self.remove_skip_color_PushButton.setObjectName("remove_skip_color_PushButton")
        self.label_48 = QtWidgets.QLabel(self.generalTab)
        self.label_48.setGeometry(QtCore.QRect(20, 300, 450, 21))
        self.label_48.setObjectName("label_48")
        self.show_ctrl_PushButton = QtWidgets.QPushButton(self.generalTab)
        self.show_ctrl_PushButton.setGeometry(QtCore.QRect(190, 180, 170, 28))
        self.show_ctrl_PushButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.show_ctrl_PushButton.setDefault(False)
        self.show_ctrl_PushButton.setObjectName("show_ctrl_PushButton")
        self.available_colors_PushButton = QtWidgets.QPushButton(self.generalTab)
        self.available_colors_PushButton.setGeometry(QtCore.QRect(350, 395, 120, 41))
        self.available_colors_PushButton.setObjectName("available_colors_PushButton")
        self.tabWidget.addTab(self.generalTab, "")
        self.paintingTab = QtWidgets.QWidget()
        self.paintingTab.setObjectName("paintingTab")
        self.pause_key_LineEdit = QtWidgets.QLineEdit(self.paintingTab)
        self.pause_key_LineEdit.setGeometry(QtCore.QRect(250, 20, 220, 22))
        self.pause_key_LineEdit.setObjectName("pause_key_LineEdit")
        self.label_10 = QtWidgets.QLabel(self.paintingTab)
        self.label_10.setGeometry(QtCore.QRect(20, 20, 220, 21))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.paintingTab)
        self.label_11.setGeometry(QtCore.QRect(20, 50, 220, 21))
        self.label_11.setObjectName("label_11")
        self.skip_key_LineEdit = QtWidgets.QLineEdit(self.paintingTab)
        self.skip_key_LineEdit.setGeometry(QtCore.QRect(250, 50, 220, 22))
        self.skip_key_LineEdit.setObjectName("skip_key_LineEdit")
        self.label_12 = QtWidgets.QLabel(self.paintingTab)
        self.label_12.setGeometry(QtCore.QRect(20, 80, 220, 21))
        self.label_12.setObjectName("label_12")
        self.abort_key_LineEdit = QtWidgets.QLineEdit(self.paintingTab)
        self.abort_key_LineEdit.setGeometry(QtCore.QRect(250, 80, 220, 22))
        self.abort_key_LineEdit.setObjectName("abort_key_LineEdit")
        self.line_2 = QtWidgets.QFrame(self.paintingTab)
        self.line_2.setGeometry(QtCore.QRect(10, 110, 460, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.update_canvas_CheckBox = QtWidgets.QCheckBox(self.paintingTab)
        self.update_canvas_CheckBox.setGeometry(QtCore.QRect(20, 140, 450, 17))
        self.update_canvas_CheckBox.setChecked(True)
        self.update_canvas_CheckBox.setObjectName("update_canvas_CheckBox")
        self.update_canvas_end_CheckBox = QtWidgets.QCheckBox(self.paintingTab)
        self.update_canvas_end_CheckBox.setGeometry(QtCore.QRect(20, 160, 450, 17))
        self.update_canvas_end_CheckBox.setChecked(True)
        self.update_canvas_end_CheckBox.setObjectName("update_canvas_end_CheckBox")
        self.opacities_CheckBox = QtWidgets.QCheckBox(self.paintingTab)
        self.opacities_CheckBox.setGeometry(QtCore.QRect(20, 340, 450, 17))
        self.opacities_CheckBox.setChecked(True)
        self.opacities_CheckBox.setObjectName("opacities_CheckBox")
        self.draw_lines_CheckBox = QtWidgets.QCheckBox(self.paintingTab)
        self.draw_lines_CheckBox.setGeometry(QtCore.QRect(20, 180, 450, 17))
        self.draw_lines_CheckBox.setChecked(True)
        self.draw_lines_CheckBox.setObjectName("draw_lines_CheckBox")
        self.line_4 = QtWidgets.QFrame(self.paintingTab)
        self.line_4.setGeometry(QtCore.QRect(10, 310, 460, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_24 = QtWidgets.QLabel(self.paintingTab)
        self.label_24.setGeometry(QtCore.QRect(40, 370, 430, 41))
        self.label_24.setObjectName("label_24")
        self.hidden_colors_CheckBox = QtWidgets.QCheckBox(self.paintingTab)
        self.hidden_colors_CheckBox.setGeometry(QtCore.QRect(20, 360, 450, 16))
        self.hidden_colors_CheckBox.setObjectName("hidden_colors_CheckBox")
        self.show_info_CheckBox = QtWidgets.QCheckBox(self.paintingTab)
        self.show_info_CheckBox.setGeometry(QtCore.QRect(20, 200, 450, 17))
        self.show_info_CheckBox.setChecked(True)
        self.show_info_CheckBox.setObjectName("show_info_CheckBox")
        self.show_preview_CheckBox = QtWidgets.QCheckBox(self.paintingTab)
        self.show_preview_CheckBox.setGeometry(QtCore.QRect(20, 220, 450, 31))
        self.show_preview_CheckBox.setChecked(True)
        self.show_preview_CheckBox.setObjectName("show_preview_CheckBox")
        self.hide_preview_CheckBox = QtWidgets.QCheckBox(self.paintingTab)
        self.hide_preview_CheckBox.setGeometry(QtCore.QRect(20, 260, 450, 16))
        self.hide_preview_CheckBox.setChecked(True)
        self.hide_preview_CheckBox.setObjectName("hide_preview_CheckBox")
        self.paint_background_CheckBox = QtWidgets.QCheckBox(self.paintingTab)
        self.paint_background_CheckBox.setGeometry(QtCore.QRect(20, 280, 450, 16))
        self.paint_background_CheckBox.setObjectName("paint_background_CheckBox")
        self.tabWidget.addTab(self.paintingTab, "")
        self.experimentalTab = QtWidgets.QWidget()
        self.experimentalTab.setObjectName("experimentalTab")
        self.label_15 = QtWidgets.QLabel(self.experimentalTab)
        self.label_15.setGeometry(QtCore.QRect(20, 20, 220, 20))
        self.label_15.setObjectName("label_15")
        self.label_19 = QtWidgets.QLabel(self.experimentalTab)
        self.label_19.setGeometry(QtCore.QRect(370, 20, 85, 20))
        self.label_19.setObjectName("label_19")
        self.click_delay_LineEdit = QtWidgets.QLineEdit(self.experimentalTab)
        self.click_delay_LineEdit.setGeometry(QtCore.QRect(250, 20, 110, 22))
        self.click_delay_LineEdit.setObjectName("click_delay_LineEdit")
        self.label_20 = QtWidgets.QLabel(self.experimentalTab)
        self.label_20.setGeometry(QtCore.QRect(370, 80, 85, 20))
        self.label_20.setObjectName("label_20")
        self.label_16 = QtWidgets.QLabel(self.experimentalTab)
        self.label_16.setGeometry(QtCore.QRect(20, 80, 220, 20))
        self.label_16.setObjectName("label_16")
        self.line_delay_LineEdit = QtWidgets.QLineEdit(self.experimentalTab)
        self.line_delay_LineEdit.setGeometry(QtCore.QRect(250, 80, 110, 22))
        self.line_delay_LineEdit.setObjectName("line_delay_LineEdit")
        self.label_21 = QtWidgets.QLabel(self.experimentalTab)
        self.label_21.setGeometry(QtCore.QRect(370, 50, 85, 20))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.experimentalTab)
        self.label_22.setGeometry(QtCore.QRect(370, 110, 85, 20))
        self.label_22.setObjectName("label_22")
        self.label_17 = QtWidgets.QLabel(self.experimentalTab)
        self.label_17.setGeometry(QtCore.QRect(20, 50, 220, 20))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.experimentalTab)
        self.label_18.setGeometry(QtCore.QRect(20, 110, 220, 20))
        self.label_18.setObjectName("label_18")
        self.min_line_width_LineEdit = QtWidgets.QLineEdit(self.experimentalTab)
        self.min_line_width_LineEdit.setGeometry(QtCore.QRect(250, 110, 110, 22))
        self.min_line_width_LineEdit.setObjectName("min_line_width_LineEdit")
        self.ctrl_delay_LineEdit = QtWidgets.QLineEdit(self.experimentalTab)
        self.ctrl_delay_LineEdit.setGeometry(QtCore.QRect(250, 50, 110, 22))
        self.ctrl_delay_LineEdit.setObjectName("ctrl_delay_LineEdit")
        self.line_5 = QtWidgets.QFrame(self.experimentalTab)
        self.line_5.setGeometry(QtCore.QRect(10, 140, 460, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.brush_type_ComboBox = QtWidgets.QComboBox(self.experimentalTab)
        self.brush_type_ComboBox.setGeometry(QtCore.QRect(250, 170, 200, 22))
        self.brush_type_ComboBox.setObjectName("brush_type_ComboBox")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/brushes/light_round.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.brush_type_ComboBox.addItem(icon, "")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/brushes/heavy_round.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.brush_type_ComboBox.addItem(icon1, "")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/brushes/medium_round.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.brush_type_ComboBox.addItem(icon2, "")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/brushes/heavy_square.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.brush_type_ComboBox.addItem(icon3, "")
        self.label_23 = QtWidgets.QLabel(self.experimentalTab)
        self.label_23.setGeometry(QtCore.QRect(20, 170, 220, 21))
        self.label_23.setObjectName("label_23")
        self.line_6 = QtWidgets.QFrame(self.experimentalTab)
        self.line_6.setGeometry(QtCore.QRect(10, 200, 460, 20))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.double_click_CheckBox = QtWidgets.QCheckBox(self.experimentalTab)
        self.double_click_CheckBox.setGeometry(QtCore.QRect(20, 230, 450, 17))
        self.double_click_CheckBox.setObjectName("double_click_CheckBox")
        self.click_color_PushButton = QtWidgets.QPushButton(self.experimentalTab)
        self.click_color_PushButton.setGeometry(QtCore.QRect(20, 390, 250, 31))
        self.click_color_PushButton.setObjectName("click_color_PushButton")
        self.brush_coords_PushButton = QtWidgets.QPushButton(self.experimentalTab)
        self.brush_coords_PushButton.setGeometry(QtCore.QRect(280, 390, 190, 31))
        self.brush_coords_PushButton.setObjectName("brush_coords_PushButton")
        self.tabWidget.addTab(self.experimentalTab, "")
        self.aboutTab = QtWidgets.QWidget()
        self.aboutTab.setObjectName("aboutTab")
        self.gitRepoLinkLabel = QtWidgets.QLabel(self.aboutTab)
        self.gitRepoLinkLabel.setGeometry(QtCore.QRect(20, 340, 221, 16))
        self.gitRepoLinkLabel.setTextFormat(QtCore.Qt.RichText)
        self.gitRepoLinkLabel.setScaledContents(False)
        self.gitRepoLinkLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.gitRepoLinkLabel.setOpenExternalLinks(True)
        self.gitRepoLinkLabel.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.gitRepoLinkLabel.setObjectName("gitRepoLinkLabel")
        self.logo1Label = QtWidgets.QLabel(self.aboutTab)
        self.logo1Label.setGeometry(QtCore.QRect(10, 30, 460, 71))
        self.logo1Label.setText("")
        self.logo1Label.setPixmap(QtGui.QPixmap(":/icons/RustDaVinci-logo-2.png"))
        self.logo1Label.setScaledContents(True)
        self.logo1Label.setObjectName("logo1Label")
        self.aboutLabel = QtWidgets.QLabel(self.aboutTab)
        self.aboutLabel.setGeometry(QtCore.QRect(20, 160, 450, 101))
        self.aboutLabel.setWordWrap(True)
        self.aboutLabel.setObjectName("aboutLabel")
        self.versionLabel = QtWidgets.QLabel(self.aboutTab)
        self.versionLabel.setGeometry(QtCore.QRect(20, 110, 161, 20))
        self.versionLabel.setObjectName("versionLabel")
        self.versionLabel_2 = QtWidgets.QLabel(self.aboutTab)
        self.versionLabel_2.setGeometry(QtCore.QRect(20, 130, 161, 20))
        self.versionLabel_2.setObjectName("versionLabel_2")
        self.licenseLabel = QtWidgets.QLabel(self.aboutTab)
        self.licenseLabel.setGeometry(QtCore.QRect(20, 270, 450, 31))
        self.licenseLabel.setWordWrap(True)
        self.licenseLabel.setObjectName("licenseLabel")
        self.line = QtWidgets.QFrame(self.aboutTab)
        self.line.setGeometry(QtCore.QRect(10, 310, 460, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.logo2Label = QtWidgets.QLabel(self.aboutTab)
        self.logo2Label.setGeometry(QtCore.QRect(250, 340, 81, 81))
        self.logo2Label.setText("")
        self.logo2Label.setPixmap(QtGui.QPixmap(":/icons/RustDaVinci-logo-1.png"))
        self.logo2Label.setScaledContents(True)
        self.logo2Label.setObjectName("logo2Label")
        self.faqLinkLabel_2 = QtWidgets.QLabel(self.aboutTab)
        self.faqLinkLabel_2.setGeometry(QtCore.QRect(20, 360, 221, 16))
        self.faqLinkLabel_2.setTextFormat(QtCore.Qt.RichText)
        self.faqLinkLabel_2.setScaledContents(False)
        self.faqLinkLabel_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.faqLinkLabel_2.setOpenExternalLinks(True)
        self.faqLinkLabel_2.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.faqLinkLabel_2.setObjectName("faqLinkLabel_2")
        self.tabWidget.addTab(self.aboutTab, "")
        self.default_PushButton = QtWidgets.QPushButton(SettingsUI)
        self.default_PushButton.setGeometry(QtCore.QRect(10, 508, 110, 28))
        self.default_PushButton.setObjectName("default_PushButton")
        self.ok_PushButton = QtWidgets.QPushButton(SettingsUI)
        self.ok_PushButton.setGeometry(QtCore.QRect(180, 508, 90, 28))
        self.ok_PushButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.ok_PushButton.setDefault(True)
        self.ok_PushButton.setObjectName("ok_PushButton")
        self.cancel_PushButton = QtWidgets.QPushButton(SettingsUI)
        self.cancel_PushButton.setGeometry(QtCore.QRect(280, 508, 90, 28))
        self.cancel_PushButton.setObjectName("cancel_PushButton")
        self.apply_PushButton = QtWidgets.QPushButton(SettingsUI)
        self.apply_PushButton.setEnabled(False)
        self.apply_PushButton.setGeometry(QtCore.QRect(380, 508, 100, 28))
        self.apply_PushButton.setObjectName("apply_PushButton")

        self.retranslateUi(SettingsUI)
        self.tabWidget.setCurrentIndex(0)
        self.quality_ComboBox.setCurrentIndex(0)
        self.brush_type_ComboBox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(SettingsUI)

    def retranslateUi(self, SettingsUI):
        _translate = QtCore.QCoreApplication.translate
        SettingsUI.setWindowTitle(_translate("SettingsUI", "Настройки RustDaVinci"))
        self.quality_ComboBox.setToolTip(_translate("SettingsUI", "Качество рисования"))
        self.quality_ComboBox.setCurrentText(_translate("SettingsUI", "Нормальное"))
        self.quality_ComboBox.setItemText(0, _translate("SettingsUI", "Нормальное"))
        self.quality_ComboBox.setItemText(1, _translate("SettingsUI", "Высокое"))
        self.label_1.setText(_translate("SettingsUI", "Качество рисования:"))
        self.monitor_Label.setText(_translate("SettingsUI", "Экран с открытым Rust:"))
        self.label_4.setText(_translate("SettingsUI", "Ширина области управления:"))
        self.label_7.setText(_translate("SettingsUI", "(в пикселях)"))
        self.label_9.setText(_translate("SettingsUI", "(в пикселях)"))
        self.ctrl_y_LineEdit.setToolTip(_translate("SettingsUI", "Y-координата левого верхнего угла области управления рисованием"))
        self.ctrl_y_LineEdit.setText(_translate("SettingsUI", "0"))
        self.clear_coords_PushButton.setToolTip(_translate("SettingsUI", "Сбросить координаты и соотношение областей управления рисованием"))
        self.clear_coords_PushButton.setText(_translate("SettingsUI", "Очистить координаты"))
        self.ctrl_h_LineEdit.setToolTip(_translate("SettingsUI", "Высота области управления рисованием"))
        self.ctrl_h_LineEdit.setText(_translate("SettingsUI", "0"))
        self.ctrl_w_LineEdit.setToolTip(_translate("SettingsUI", "Ширина области управления рисованием"))
        self.ctrl_w_LineEdit.setText(_translate("SettingsUI", "0"))
        self.label_2.setText(_translate("SettingsUI", "X-координата области управления:"))
        self.label_8.setText(_translate("SettingsUI", "(в пикселях)"))
        self.label_6.setText(_translate("SettingsUI", "(в пикселях)"))
        self.ctrl_x_LineEdit.setToolTip(_translate("SettingsUI", "X-координата левого верхнего угла области управления рисованием"))
        self.ctrl_x_LineEdit.setText(_translate("SettingsUI", "0"))
        self.label_5.setText(_translate("SettingsUI", "Высота области управления:"))
        self.label_3.setText(_translate("SettingsUI", "Y-координата области управления:"))
        self.topmost_CheckBox.setToolTip(_translate("SettingsUI", "Окно RustDaVinci будет всегда поверх других во время рисования"))
        self.topmost_CheckBox.setText(_translate("SettingsUI", "Закрепить окно RustDaVinci поверх других при рисовании"))
        self.skip_background_CheckBox.setToolTip(_translate("SettingsUI", "Пропустить закрашивание заданным цветом фона"))
        self.skip_background_CheckBox.setText(_translate("SettingsUI", "Не закрашивать области цветом фона"))
        self.label_13.setText(_translate("SettingsUI", "Цвет фона по умолчанию:"))
        self.color_picker_PushButton.setToolTip(_translate("SettingsUI", "Открыть поиск цвета"))
        self.color_picker_PushButton.setText(_translate("SettingsUI", "..."))
        self.background_LineEdit.setToolTip(_translate("SettingsUI", "Текущий HEX-цвет фона по умолчанию"))
        self.background_LineEdit.setText(_translate("SettingsUI", "#ECF0F1"))
        self.skip_colors_ListWidget.setToolTip(_translate("SettingsUI", "Список цветов, которые будут пропускаться при рисовании"))
        self.add_skip_color_PushButton.setToolTip(_translate("SettingsUI", "Добавить цвета в список пропускаемых при рисовании"))
        self.add_skip_color_PushButton.setText(_translate("SettingsUI", "Добавить"))
        self.remove_skip_color_PushButton.setToolTip(_translate("SettingsUI", "Удалить выбранный цвет из списка пропускаемых"))
        self.remove_skip_color_PushButton.setText(_translate("SettingsUI", "Удалить"))
        self.label_48.setText(_translate("SettingsUI", "Пропускать следующие цвета:"))
        self.show_ctrl_PushButton.setToolTip(_translate("SettingsUI", "Показать на экране область элементов управления по координатам и соотношению"))
        self.show_ctrl_PushButton.setText(_translate("SettingsUI", "Показать элементы"))
        self.available_colors_PushButton.setToolTip(_translate("SettingsUI", "Открыть окно со всеми доступными цветами RustDaVinci"))
        self.available_colors_PushButton.setText(_translate("SettingsUI", "Доступные цвета"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.generalTab), _translate("SettingsUI", "Основные"))
        self.pause_key_LineEdit.setToolTip(_translate("SettingsUI", "Горячая клавиша для паузы и продолжения процесса рисования"))
        self.pause_key_LineEdit.setText(_translate("SettingsUI", "f10"))
        self.label_10.setText(_translate("SettingsUI", "Горячая клавиша паузы:"))
        self.label_11.setText(_translate("SettingsUI", "Горячая клавиша пропуска цвета:"))
        self.skip_key_LineEdit.setToolTip(_translate("SettingsUI", "Горячая клавиша для пропуска текущего цвета"))
        self.skip_key_LineEdit.setText(_translate("SettingsUI", "f11"))
        self.label_12.setText(_translate("SettingsUI", "Горячая клавиша отмены:"))
        self.abort_key_LineEdit.setToolTip(_translate("SettingsUI", "Горячая клавиша для прекращения процесса рисования"))
        self.abort_key_LineEdit.setText(_translate("SettingsUI", "esc"))
        self.update_canvas_CheckBox.setToolTip(_translate("SettingsUI", "Автоматически обновлять холст при смене цвета во время рисования"))
        self.update_canvas_CheckBox.setText(_translate("SettingsUI", "Автоматически обновлять холст во время рисования"))
        self.update_canvas_end_CheckBox.setToolTip(_translate("SettingsUI", "Автоматически обновлять холст по завершении рисования"))
        self.update_canvas_end_CheckBox.setText(_translate("SettingsUI", "Автоматически сохранять рисунок после завершения"))
        self.opacities_CheckBox.setToolTip(_translate("SettingsUI", "Улучшает рисунки за счёт использования разных значений прозрачности кисти"))
        self.opacities_CheckBox.setText(_translate("SettingsUI", "Улучшать рисунки, используя разные значения прозрачности кисти"))
        self.draw_lines_CheckBox.setToolTip(_translate("SettingsUI", "Группы пикселей будут рисоваться линией вместо отдельных точек (ускоряет рисование)"))
        self.draw_lines_CheckBox.setText(_translate("SettingsUI", "Рисовать линии, если это быстрее"))
        self.label_24.setText(_translate("SettingsUI", "(Рекомендуется только при разрешении 1920x1080 в игре\n"
"и автоматическом определении области управления)"))
        self.hidden_colors_CheckBox.setToolTip(_translate("SettingsUI", "Улучшает рисунки за счёт использования скрытых цветов (между видимыми кругами палитры)"))
        self.hidden_colors_CheckBox.setText(_translate("SettingsUI", "Использовать скрытую палитру цветов"))
        self.show_info_CheckBox.setToolTip(_translate("SettingsUI", "Показывать информацию о рисовании (цвета, пиксели, линии) перед стартом"))
        self.show_info_CheckBox.setText(_translate("SettingsUI", "Показывать информацию о рисовании перед запуском"))
        self.show_preview_CheckBox.setToolTip(_translate("SettingsUI", "Автоматически показывать превью в зависимости от качества при загрузке нового изображения"))
        self.show_preview_CheckBox.setText(_translate("SettingsUI", "Автоматически показывать превью в зависимости от качества\n"
"при загрузке нового изображения"))
        self.hide_preview_CheckBox.setToolTip(_translate("SettingsUI", "Автоматически скрывать превью при старте рисования"))
        self.hide_preview_CheckBox.setText(_translate("SettingsUI", "Автоматически скрывать превью перед началом рисования"))
        self.paint_background_CheckBox.setToolTip(_translate("SettingsUI", "Автоматически закрасить фон заданным цветом перед началом рисования"))
        self.paint_background_CheckBox.setText(_translate("SettingsUI", "Автоматически закрашивать фон при старте"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.paintingTab), _translate("SettingsUI", "Рисование"))
        self.label_15.setText(_translate("SettingsUI", "Задержка клика мышью:"))
        self.label_19.setText(_translate("SettingsUI", "(мс)"))
        self.click_delay_LineEdit.setToolTip(_translate("SettingsUI", "Задержка отпускания кнопки мыши при клике. Увеличение повышает точность, но снижает скорость."))
        self.click_delay_LineEdit.setText(_translate("SettingsUI", "15"))
        self.label_20.setText(_translate("SettingsUI", "(мс)"))
        self.label_16.setText(_translate("SettingsUI", "Задержка рисования линий:"))
        self.line_delay_LineEdit.setToolTip(_translate("SettingsUI", "Задержка при рисовании линии. Увеличение повышает точность, но снижает скорость."))
        self.line_delay_LineEdit.setText(_translate("SettingsUI", "25"))
        self.label_21.setText(_translate("SettingsUI", "(мс)"))
        self.label_22.setText(_translate("SettingsUI", "(пикс.)"))
        self.label_17.setText(_translate("SettingsUI", "Задержка между элементами управления:"))
        self.label_18.setText(_translate("SettingsUI", "Минимальная длина линии:"))
        self.min_line_width_LineEdit.setToolTip(_translate("SettingsUI", "Минимальное количество сгруппированных пикселей для рисования линии. Влияет на время рисования."))
        self.min_line_width_LineEdit.setText(_translate("SettingsUI", "10"))
        self.ctrl_delay_LineEdit.setToolTip(_translate("SettingsUI", "Задержка между кликами по разным элементам управления"))
        self.ctrl_delay_LineEdit.setText(_translate("SettingsUI", "150"))
        self.brush_type_ComboBox.setToolTip(_translate("SettingsUI", "Тип кисти по умолчанию для рисования"))
        self.brush_type_ComboBox.setCurrentText(_translate("SettingsUI", "Тяжёлая круглая"))
        self.brush_type_ComboBox.setItemText(0, _translate("SettingsUI", "Лёгкая круглая"))
        self.brush_type_ComboBox.setItemText(1, _translate("SettingsUI", "Тяжёлая круглая"))
        self.brush_type_ComboBox.setItemText(2, _translate("SettingsUI", "Средняя круглая"))
        self.brush_type_ComboBox.setItemText(3, _translate("SettingsUI", "Тяжёлая квадратная"))
        self.label_23.setText(_translate("SettingsUI", "Тип кисти для рисования:"))
        self.double_click_CheckBox.setToolTip(_translate("SettingsUI", "Автоматически кликать мышью дважды, устраняя «мёртвые» пиксели"))
        self.double_click_CheckBox.setText(_translate("SettingsUI", "Двойной клик мышью для улучшения точности"))
        self.click_color_PushButton.setToolTip(_translate("SettingsUI", "Открыть диалог выбора цвета, по которому приложение кликнет в игровой палитре"))
        self.click_color_PushButton.setText(_translate("SettingsUI", "Клик по цвету"))
        self.brush_coords_PushButton.setToolTip(_translate("SettingsUI", "Настроить координаты и ввод значений кисти/HEX для внешней палитры"))
        self.brush_coords_PushButton.setText(_translate("SettingsUI", "Координаты кисти / HEX"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.experimentalTab), _translate("SettingsUI", "Экспериментальные"))
        self.gitRepoLinkLabel.setToolTip(_translate("SettingsUI", "https://github.com/alexemanuelol/RustDaVinci"))
        self.gitRepoLinkLabel.setText(_translate("SettingsUI", "<html><head/><body><p><a href=\"https://github.com/alexemanuelol/RustDaVinci\"><span style=\" font-weight:600; text-decoration: underline; color:#000000;\">Репозиторий GitHub</span></a></p></body></html>"))
        self.aboutLabel.setText(_translate("SettingsUI", "RustDaVinci — автоматический рисовальщик табличек для игры Rust от Facepunch. Приложение полностью бесплатно и с открытым исходным кодом. Если вы хотите помочь в разработке, посетите страницу GitHub по ссылке ниже. Рекомендуется использовать только опубликованные релизные версии, чтобы избежать проблем с EAC / Facepunch. Последние релизы доступны на GitHub."))
        self.versionLabel.setText(_translate("SettingsUI", "v0.4.0"))
        self.versionLabel_2.setText(_translate("SettingsUI", "6 марта 2020"))
        self.licenseLabel.setText(_translate("SettingsUI", "RustDaVinci распространяется по лицензии GNU GPL3\n"
"Разработчик: AlexEmanuelol"))
        self.faqLinkLabel_2.setToolTip(_translate("SettingsUI", "https://github.com/alexemanuelol/RustDaVinci/blob/master/docs/FAQ.md"))
        self.faqLinkLabel_2.setText(_translate("SettingsUI", "<html><head/><body><p><a href=\"https://github.com/alexemanuelol/RustDaVinci/blob/master/docs/FAQ.md\"><span style=\" font-weight:600; text-decoration: underline; color:#000000;\">Часто задаваемые вопросы</span></a></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.aboutTab), _translate("SettingsUI", "О программе"))
        self.default_PushButton.setToolTip(_translate("SettingsUI", "Вернуть все настройки к значениям по умолчанию"))
        self.default_PushButton.setText(_translate("SettingsUI", "По умолчанию"))
        self.ok_PushButton.setText(_translate("SettingsUI", "ОК"))
        self.cancel_PushButton.setText(_translate("SettingsUI", "Отмена"))
        self.apply_PushButton.setText(_translate("SettingsUI", "Применить"))
import ui.resources.icons_rc
